# Generated by Django 2.1.5 on 2019-01-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_name', models.CharField(max_length=30)),
                ('dish_name', models.CharField(max_length=30)),
                ('desert_name', models.CharField(max_length=30)),
                ('starter_calories', models.FloatField()),
                ('dish_calories', models.FloatField()),
                ('desert_calories', models.FloatField()),
                ('sum_calories', models.FloatField()),
            ],
        ),
    ]
